### ISSUE TITLE
Olá, bom dia

### ISSUE THREAD

**Issue by stherzada** [CarlosJunioor/my-portofolio#1]
Olá tudo bem? Como está seu dia? Bom, gostaria de saber como posso acessar seus portfolio. Estou meio perdida quanto a isso,,, 

Grata <3

**Comment by CarlosJunioor** [comment]
Hi @stherzada, thank you for opening this issue, in fact for due the lack of time/work, wasn't able to maintain the repo.

Glad you notice this, had to translate what you said because im not Portuguese.

Link to my website is on the readme.
